import React from "react";

// Sample meals data with comprehensive meal options organized by meal time
// and with appropriate tags to support filtering
const PreMadeMeals = [

  // Breakfast options
  {
    time: "Breakfast",
    name: "Oatmeal with Fresh Berries and Almonds",
    calories: 387,
    protein: 12,
    carbs: 45,
    fats: 10,
    notes: "Add peanut butter for extra protein.",
    image: 'oatmeal.png',
    description: "A hearty breakfast bowl full of fiber and antioxidants.",
    ingredients: "Rolled oats, fresh berries, sliced almonds, honey, milk",
    tags: ["High carb", "Healthy", "Fruity"]
  },
  {
    time: "Breakfast",
    name: "Avocado Toast with Poached Eggs",
    calories: 420,
    protein: 18,
    carbs: 32,
    fats: 24,
    notes: "Use whole grain bread for added fiber.",
    image: 'avocadotoast.png',
    description: "The perfect balance of healthy fats and protein to start your day.",
    ingredients: "Whole grain bread, avocado, eggs, cherry tomatoes, microgreens, salt, pepper",
    tags: ["Healthy", "Gains"]
  },
  {
    time: "Breakfast",
    name: "Vegan Breakfast Bowl",
    calories: 340,
    protein: 14,
    carbs: 48,
    fats: 12,
    notes: "Add nutritional yeast for B vitamins.",
    image: 'veganbowl.png',
    description: "Plant-based power breakfast with complete proteins.",
    ingredients: "Tofu scramble, black beans, sweet potatoes, spinach, avocado, salsa",
    tags: ["Vegan", "Healthy"]
  },
  {
    time: "Breakfast",
    name: "Protein Pancakes with Berries",
    calories: 450,
    protein: 30,
    carbs: 52,
    fats: 8,
    notes: "Top with Greek yogurt for extra protein.",
    image: 'berrypancakes.png',
    description: "Fluffy pancakes packed with muscle-building protein.",
    ingredients: "Protein powder, oat flour, egg whites, almond milk, baking powder, vanilla extract, mixed berries",
    tags: ["High carb", "Gains", "Fruity"]
  },
  {
    "time": "Breakfast",
    "name": "Strawberry Crepes",
    "calories": 430,
    "protein": 10,
    "carbs": 58,
    "fats": 18,
    "notes": "Best served fresh with a light dusting of powdered sugar.",
    "image": "crepes.png",
    "description": "Delicate French-style crepes filled with fresh strawberries and cream, lightly dusted with powdered sugar.",
    "ingredients": "Flour, eggs, milk, butter, strawberries, whipped cream, powdered sugar, vanilla extract",
    "tags": ["Sweet", "Light", "Brunch"]
  },

    {
      "time": "Breakfast",
      "name": "Classic Bacon and Eggs",
      "calories": 450,
      "protein": 25,
      "carbs": 2,
      "fats": 38,
      "notes": "Crispy bacon paired with sunny-side-up eggs.",
      "image": "bacon.png",
      "description": "A hearty, protein-rich breakfast featuring crispy bacon strips and perfectly cooked eggs.",
      "ingredients": "Bacon, eggs, butter, salt, pepper",
      "tags": ["Hearty", "Keto-Friendly"]
    },
    {
      "time": "Breakfast",
      "name": "Berry Waffles",
      "calories": 520,
      "protein": 12,
      "carbs": 65,
      "fats": 22,
      "notes": "Top with maple syrup for extra sweetness.",
      "image": "waffles.png",
      "description": "Golden, fluffy waffles topped with a mix of fresh berries and a dusting of powdered sugar.",
      "ingredients": "Flour, eggs, milk, butter, sugar, strawberries, blueberries, powdered sugar",
      "tags": ["Sweet", "Brunch", "Family Favorite"]
    },
    {
      "time": "Breakfast",
      "name": "Ham and Eggs Breakfast Plate",
      "calories": 520,
      "protein": 30,
      "carbs": 15,
      "fats": 38,
      "notes": "Includes a light salad and dressing for balance.",
      "image": "ham.png",
      "description": "Sliced ham served with sunny-side-up eggs, fresh greens, and a touch of dressing.",
      "ingredients": "Ham, eggs, lettuce, dressing, bread, butter",
      "tags": ["Savory", "Balanced"]
    },
    {
      "time": "Breakfast",
      "name": "Veggie Omelette",
      "calories": 400,
      "protein": 22,
      "carbs": 6,
      "fats": 30,
      "notes": "Can add extra vegetables or cheese to customize.",
      "image": "omelette.png",
      "description": "Fluffy omelette packed with spinach, tomatoes, and herbs, served with a light salad.",
      "ingredients": "Eggs, spinach, tomatoes, herbs, olive oil, cheese (optional)",
      "tags": ["High-Protein", "Vegetarian", "Healthy"]
    },
  
  // Lunch options
  {
    time: "Lunch",
    name: "Salmon with Lemon and Spinach",
    calories: 487,
    protein: 35,
    carbs: 8,
    fats: 32,
    notes: "Add lemon for taste and vitamin C.",
    image: 'salmon2.png',
    description: "Omega-3 rich fish with leafy greens for a nutritious lunch.",
    ingredients: "Wild caught salmon, fresh spinach, lemon, garlic, olive oil",
    tags: ["Seafood", "Healthy", "Gains"]
  },
  {
    time: "Lunch",
    name: "Quinoa Buddha Bowl",
    calories: 520,
    protein: 16,
    carbs: 78,
    fats: 14,
    notes: "Adjust grains to preference.",
    image: 'buddha-bowl.png',
    description: "Nutrient-dense bowl with a rainbow of vegetables and complete protein.",
    ingredients: "Quinoa, roasted sweet potatoes, chickpeas, avocado, kale, tahini dressing",
    tags: ["Vegan", "Healthy", "High carb"]
  },
  {
    time: "Lunch",
    name: "Spicy Shrimp Tacos",
    calories: 410,
    protein: 28,
    carbs: 36,
    fats: 16,
    notes: "Use corn tortillas for gluten-free option.",
    image: 'shrimp-tacos.png',
    description: "Zesty seafood tacos with fresh cabbage slaw.",
    ingredients: "Shrimp, corn tortillas, cabbage, lime, cilantro, jalapeño, avocado",
    tags: ["Seafood", "Spicy"]
  },
  {
    time: "Lunch",
    name: "Mediterranean Chicken Wrap",
    calories: 490,
    protein: 32,
    carbs: 45,
    fats: 18,
    notes: "Use hummus instead of mayo for healthier fats.",
    image: 'chicken-wrap.png',
    description: "Protein-packed wrap with Mediterranean flavors.",
    ingredients: "Grilled chicken breast, whole wheat wrap, hummus, cucumber, tomato, feta cheese, olives",
    tags: ["Healthy", "Gains"]
  },
  {
    time: "Lunch",
    name: "High-Protein Pasta Salad",
    calories: 530,
    protein: 28,
    carbs: 65,
    fats: 14,
    notes: "Can be made ahead for meal prep.",
    image: 'pasta-salad.png',
    description: "Cold pasta dish perfect for post-workout recovery.",
    ingredients: "Whole grain pasta, grilled chicken, cherry tomatoes, cucumber, bell pepper, feta cheese, Italian dressing",
    tags: ["High carb", "Gains"]
  },
  
  // Dinner options
  {
    time: "Dinner",
    name: "Grilled Steak with Vegetables",
    calories: 580,
    protein: 42,
    carbs: 20,
    fats: 32,
    notes: "Use grass-fed beef when possible.",
    image: 'steakveg.png',
    description: "Classic muscle-building dinner with essential nutrients.",
    ingredients: "Sirloin steak, roasted broccoli, carrots, bell peppers, olive oil, garlic, herbs",
    tags: ["Gains", "Healthy"]
  },
  {
    time: "Dinner",
    name: "Pasta with Tomatoes and Cheese",
    calories: 500,
    protein: 18,
    carbs: 70,
    fats: 15,
    notes: "Add grilled chicken for extra protein.",
    image: 'pasta.png',
    description: "Comfort food with a healthy twist.",
    ingredients: "Whole grain pasta, cherry tomatoes, low-fat cheese, basil, garlic",
    tags: ["High carb", "Healthy"]
  },
  {
    time: "Dinner",
    name: "Vegan Curry with Rice",
    calories: 480,
    protein: 14,
    carbs: 75,
    fats: 12,
    notes: "Adjust spice level to taste.",
    image: 'vegan-curry.png',
    description: "Plant-based curry packed with flavor and nutrients.",
    ingredients: "Chickpeas, coconut milk, mixed vegetables, curry spices, brown rice",
    tags: ["Vegan", "Spicy", "High carb"]
  },
  {
    time: "Dinner",
    name: "Baked Cod with Lemon Herb Crust",
    calories: 320,
    protein: 38,
    carbs: 12,
    fats: 14,
    notes: "Serve with a side of quinoa or brown rice.",
    image: 'baked-cod.png',
    description: "Light yet satisfying seafood dinner with bright flavors.",
    ingredients: "Cod fillets, breadcrumbs, lemon zest, parsley, dill, olive oil",
    tags: ["Seafood", "Healthy"]
  },
  {
    time: "Dinner",
    name: "Spicy Korean Beef Bowl",
    calories: 550,
    protein: 35,
    carbs: 50,
    fats: 22,
    notes: "Add kimchi for probiotics.",
    image: 'korean-beef.png',
    description: "Flavorful beef bowl with a fiery kick.",
    ingredients: "Ground beef, brown rice, gochujang paste, soy sauce, sesame oil, vegetables",
    tags: ["Spicy", "Gains"]
  },
  
  // Snack options
  {
    time: "Snack",
    name: "Greek Yogurt & Berries",
    calories: 200,
    protein: 15,
    carbs: 20,
    fats: 5,
    notes: "Use low-fat yogurt to reduce calories.",
    image: 'yogurt2.png',
    description: "Protein-packed snack with antioxidant-rich berries.",
    ingredients: "Greek yogurt, mixed berries, honey, chia seeds",
    tags: ["Healthy", "Fruity"]
  },
  {
    time: "Snack",
    name: "Protein Smoothie",
    calories: 280,
    protein: 25,
    carbs: 30,
    fats: 6,
    notes: "Add spinach for extra nutrients without changing taste.",
    image: 'protein-smoothie.png',
    description: "Refreshing post-workout drink to fuel muscle recovery.",
    ingredients: "Protein powder, banana, milk, peanut butter, ice",
    tags: ["Gains", "Fruity"]
  },
  {
    time: "Snack",
    name: "Spicy Roasted Chickpeas",
    calories: 180,
    protein: 9,
    carbs: 27,
    fats: 5,
    notes: "Store in airtight container to maintain crispness.",
    image: 'roasted-chickpeas.png',
    description: "Crunchy, protein-rich snack with a kick.",
    ingredients: "Chickpeas, olive oil, chili powder, cumin, paprika, garlic powder",
    tags: ["Vegan", "Spicy"]
  },
  {
    time: "Snack",
    name: "Avocado and Shrimp Rice Cakes",
    calories: 210,
    protein: 12,
    carbs: 18,
    fats: 11,
    notes: "Use brown rice cakes for more fiber.",
    image: 'shrimp-rice-cakes.png',
    description: "Light yet satisfying snack with heart-healthy fats.",
    ingredients: "Rice cakes, avocado, cooked shrimp, lemon juice, red pepper flakes",
    tags: ["Seafood", "Healthy"]
  },
  {
    time: "Snack",
    name: "Banana Oat Energy Balls",
    calories: 150,
    protein: 5,
    carbs: 25,
    fats: 4,
    notes: "Freeze for longer storage.",
    image: 'energy-balls.png',
    description: "Natural energy boost with slow-release carbs.",
    ingredients: "Oats, mashed banana, peanut butter, honey, cinnamon, chocolate chips",
    tags: ["Vegan", "High carb", "Fruity"]
  },
  {
    time: "2nd breakfast",
    name: "Avocado Tomato Sandwich",
    calories: 320,
    protein: 8,
    carbs: 30,
    fats: 20,
    notes: "",
    image: 'avocadotomatoes.png',
    description: "A fresh and nutritious sandwich made with creamy avocado and juicy tomatoes, perfect for a light second breakfast.",
    ingredients: "Whole-grain bread, avocado, tomato slices, olive oil, salt, pepper",
    tags: ["Vegan", "Healthy"]
  },
  {
    time: "2nd breakfast",
    name: "Bowl of Berries",
    calories: 150,
    protein: 2,
    carbs: 35,
    fats: 1,
    notes: "",
    image: 'berries.png',
    description: "A vibrant bowl of assorted fresh berries, rich in antioxidants and vitamins.",
    ingredients: "Strawberries, blueberries, raspberries, blackberries",
    tags: ["Fruity", "Healthy"]
  },
  {
    time: "2nd breakfast",
    name: "Bowl of Cereal",
    calories: 250,
    protein: 6,
    carbs: 45,
    fats: 5,
    notes: "",
    image: 'cereal.png',
    description: "Classic bowl of cereal served with milk for a quick and easy energy boost.",
    ingredients: "Whole grain cereal, milk (or plant-based milk)",
    tags: ["High carb", "Healthy"]
  },
  
  {
    time: "2nd breakfast",
    name: "Granola with Yogurt and Fruits",
    calories: 380,
    protein: 12,
    carbs: 40,
    fats: 18,
    notes: "",
    image: 'granola.png',
    description: "Crunchy granola paired with creamy yogurt and sweet fruits for a delicious and balanced meal.",
    ingredients: "Granola, Greek yogurt, mixed fruits (berries, banana, apple)",
    tags: ["Fruity", "Gains"]
  },
  {
    time: "2nd breakfast",
    name: "Pancakes with Banana and Honey",
    calories: 420,
    protein: 9,
    carbs: 60,
    fats: 12,
    notes: "",
    image: 'pancakebanana.png',
    description: "Fluffy pancakes topped with ripe banana slices and drizzled with natural honey.",
    ingredients: "Pancake batter, banana, honey, butter (optional)",
    tags: ["High carb", "Fruity"]
  },
  {
    time: "2nd breakfast",
    name: "Scrambled Eggs with Spinach",
    calories: 270,
    protein: 16,
    carbs: 4,
    fats: 20,
    notes: "",
    image: 'scrambledeggs.png',
    description: "Soft scrambled eggs mixed with fresh spinach for a protein-packed breakfast.",
    ingredients: "Eggs, spinach, butter or olive oil, salt, pepper",
    tags: ["Gains", "Healthy"]
  } 
];

export default PreMadeMeals;